### PR TITLE
Notification module backend logic - REDO

### PR DESCRIPTION
**Pull request by WyattLamberth**
added update, reminder and create events for notification tab

### CODE REVIEW

**Comment by WyattLamberth** [comment]
We should retest this before we merge.

**Comment by akren20** [comment]
I'm currently getting errors, I'm going to look into what's happening when I try and start the server
image

**Comment by WyattLamberth** [comment]
Wasn't sure what .mjs files were, changed file name server.js -> server.mjs
hopefully should fix the issue.

**Comment by akren20** [comment]
> Wasn't sure what .mjs files were, changed file name server.js -> server.mjs hopefully should fix the issue.

I was just about to do that, glad it was a simple fix

**Comment by akren20** [comment]
@WyattLamberth I think everything looks good now with no errors. All of the tests are passing as well. We should all also see how to generate test reports with Mocha before we submit assignment 3
image

**Comment by akren20** [comment]
We should also Rebase and Merge in case this branch does not have all the latest commits

**Comment by WyattLamberth** [comment]
I tried rebasing to fix the merge conflicts earlier but it was giving me some weird stuff, probably will work better now without errors lol. also yeah we can make a script to do testing or something.

**Comment by WyattLamberth** [comment]
@xavidiaz100 10/10 branch

**Pull request merged**
